version: "3.7"
services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    env_file:
      - redis.env
    ports:
      - "6379:6379"

  scheduler:
    container_name: scheduler
    image: scheduler
    build:
      dockerfile: Dockerfile
      context: .
    # volumes:
    #   - ./scheduler_vol:/app/
    depends_on:
      - redis
    ports:
      - "3000:3000"
    restart: always
    environment:
      - REDIS_HOST=redis
    env_file:
      - redis.env

  schedule_runner:
    container_name: schedule-runner
    image: schedule-runner
    build:
      dockerfile: scheduler/Dockerfile
      context: .
    # volumes:
    #   - ./schedule_runner_vol/:/app/scheduler
    depends_on:
      - redis
    restart: always
    environment:
      - REDIS_HOST=redis
    env_file:
      - redis.env
